on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Upgrade NPM
        if: ${{ matrix.node-version == '12.x' || matrix.node-version == '14.x' }}
        run: npm i -g npm@8 --registry=https://registry.npmjs.org
      - name: Install
        run: npm ci
      - name: Lint and Test
        run: |
          npm run lint
          npm test

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }} # publish only from master
    needs: [build]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GIT_PUSH_TOKEN }}
    - name: Configure CI user
      run: |
        git config user.email "ci@sclable.com"
        git config user.name "Sclable CI"
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - name: Install and generate docs
      run: npm ci
    - name: Publish
      env:
        NPM_TOKEN: ${{ secrets.NPMJS_REGISTRY_TOKEN }}
      run: |
        echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        npx lerna publish -y
    - name: Generate documentation
      run: npx typedoc
    - name: Save documentation
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs
        retention-days: 1
  docs:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [publish]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ${{github.repository}}.wiki
        token: ${{ secrets.GIT_PUSH_TOKEN }}
    - name: Configure CI user
      run: |
        git config user.email "ci@sclable.com"
        git config user.name "Sclable CI"
    - name: Load documentation
      uses: actions/download-artifact@v2
      with:
        name: docs
        path: .
    - name: Commit and push
      run: |
        git add .
        git commit -am "Update documentation"
        git push origin master

